import React from "react";

// layout imports

import type { Metadata } from "next";
import { Inter } from "next/font/google";

// CSS Imports
// import "./globals.css";
import "../public/assets/img/favicon.png";
import "../public/assets/css/style.css";
import "../public/assets/sass/style.scss";
import "../public/assets/css/font-icons.css";
import "../public/assets/css/plugins.css";
import "../public/assets/css/responsive.css";

// JS Imports
import Script from "next/script";
// import "../public/assets/js/plugins";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Real Estate React Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="quarter-overlay">
          <div className="cv-spinner">
            <span className="spinner"></span>
          </div>
        </div>

        <div className="page-wrapper">
          <div id="quarter"></div>
        </div>

        {children}

        {/* <Script src="https://code.jquery.com/jquery-3.2.1.min.js" /> */}
        <Script src="/assets/js/plugins.js" async />
      </body>
    </html>
  );
}
